### ISSUE TITLE
getting file not found error when i run train.py even when i m having file

### ISSUE THREAD

**Issue by anchalrani** [Kyubyong/expressive_tacotron#14]
(tf-gpu) [pranaw@login expressive_tacotron-master]$ python train.py 
Traceback (most recent call last):
  File "train.py", line 101, in <module>
    g = Graph(); print("Training Graph loaded")
  File "train.py", line 35, in __init__
    self.x, self.y, self.z, self.fnames, self.num_batch = get_batch()
  File "/home/pranaw/TTS/expressive_tacotron-master/data_load.py", line 65, in get_batch
    fpaths, texts = load_data() # list
  File "/home/pranaw/TTS/expressive_tacotron-master/data_load.py", line 40, in load_data
    lines = codecs.open(transcript, 'r', 'utf-8').readlines()
  File "/home/pranaw/TTS/anaconda3/envs/tf-gpu/lib/python3.6/codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/data/private/voice/LJSpeech-1.0/metadata.csv'

**Comment by djebel-amila** [comment]
I had to remove the first "/", at the beginning of the url for the path to work. In hyperparams.py, line 16, replace
`test_data = '/data/private/voice/LJSpeech-1.0/metadata.csv' `
by
`test_data = 'data/private/voice/LJSpeech-1.0/metadata.csv' `
